### ISSUE TITLE
内容都是空的

### ISSUE THREAD

**Issue by ZhangXinRuiJava** [waylau/jdbc-specification#4]
![文档内容为空](https://user-images.githubusercontent.com/38937932/168001636-75011d78-88a5-45b2-9673-edcc88a7ee46.png)
文档内容很多都是空的

**Comment by waylau** [comment]
@ZhangXinRuiJava  暂时只完成了  [13.Statements.md](https://github.com/waylau/jdbc-specification/blob/master/13.Statements.md)
